---
name: Test-Run-Plugin-TrimDisplayedFilenames
version: 0.0121
author:
  - 'Shlomi Fish <shlomif@cpan.org>'
abstract: |-
  trim the first components
  of the displayed filename to deal with excessively long ones.
license: mit
resources:
  license: http://www.opensource.org/licenses/mit-license.php
build_requires:
  Test::More: 0
  Test::Run::CmdLine::Trap::ProveApp: 0
  Test::Trap: 0
requires:
  MRO::Compat: 0
  Moose: 0
  Test::Run::CmdLine: 0.0120
  Test::Run::Core: 0.0121
configure_requires:
  Module::Build: 0.35
provides:
  Test::Run::CmdLine::Plugin::TrimDisplayedFilenames:
    file: lib/Test/Run/CmdLine/Plugin/TrimDisplayedFilenames.pm
    version: 0.0121
  Test::Run::Plugin::TrimDisplayedFilenames:
    file: lib/Test/Run/Plugin/TrimDisplayedFilenames.pm
    version: 0.0121
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
