---
abstract: "trim the first components\nof the displayed filename to deal with excessively long ones."
author:
  - 'Shlomi Fish <shlomif@cpan.org>'
build_requires:
  Test::More: 0
  Test::Run::CmdLine::Trap::ProveApp: 0
  Test::Trap: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Run-Plugin-TrimDisplayedFilenames
provides:
  Test::Run::CmdLine::Plugin::TrimDisplayedFilenames:
    file: lib/Test/Run/CmdLine/Plugin/TrimDisplayedFilenames.pm
    version: 0.0122
  Test::Run::Plugin::TrimDisplayedFilenames:
    file: lib/Test/Run/Plugin/TrimDisplayedFilenames.pm
    version: 0.0122
requires:
  MRO::Compat: 0
  Moose: 0
  Test::Run::CmdLine: 0.0121
  Test::Run::Core: 0.0122
resources:
  license: http://www.opensource.org/licenses/mit-license.php
version: 0.0122
